on: push
name: Flutter CI
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi

  coverage:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.7

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Collect coverage
        run: |
          pub global activate test_coverage
          pub global run test_coverage
      - uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV }}
          file: dartx/coverage/lcov.info